version: '3.4'

services:
  chatwithgpt:
    image: chatwithgpt
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4230:4230
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
